In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 15 01:15:20 2020

@author: Shoum
"""

# Logistic Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score

# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)

# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_val)
loss = log_loss(y_val, y_pred)
print(loss)
cm = confusion_matrix(y_val, y_pred)
print(cm)
accuracy_score(y_val, y_pred)


# Training K nearest neighbour
from sklearn.neighbors import KNeighborsClassifier
classifier_KNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_KNN.fit(X_train, y_train)
knn_pred = classifier_KNN.predict(X_val)
knn_loss = log_loss(y_val, knn_pred)
print(knn_loss)
knn_cm = confusion_matrix(y_val, knn_pred)
print(knn_cm)
accuracy_score(y_val, knn_pred)

#Support Vecotr Machine
from sklearn.svm import SVC
classifier_SVC = SVC(kernel = 'linear', random_state = 0)
classifier_SVC.fit(X_train, y_train)
svc_pred = classifier_SVC.predict(X_val)
svc_loss = log_loss(y_val, svc_pred)
print(loss)
svc_cm = confusion_matrix(y_val, svc_pred)
print(svc_cm)
accuracy_score(y_val, svc_pred)



# Kernal Support vector machine

classifier_svc2 = SVC(kernel = 'rbf', random_state = 0)
classifier_svc2.fit(X_train, y_train)
svc2_pred = classifier_svc2.predict(X_val)
svc2_loss = log_loss(y_val, svc2_pred)
print(svc2_loss)
svc2_cm = confusion_matrix(y_val, svc2_pred)
print(cm)
accuracy_score(y_val, svc2_pred)

# Naive Bayes

from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(X_train, y_train)
nb_pred = classifier_nb.predict(X_val)
nb_loss = log_loss(y_val, nb_pred)
print(nb_loss)
nb_cm = confusion_matrix(y_val, nb_pred)
print(nb_cm)
accuracy_score(y_val, nb_pred)

# Decision Tree

from sklearn.tree import DecisionTreeClassifier
classifier_tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_tree.fit(X_train, y_train)
tree_pred = classifier_tree.predict(X_val)
tree_loss = log_loss(y_val, tree_pred)
print(tree_loss)
tree_cm = confusion_matrix(y_val, tree_pred) 
print(tree_cm)
accuracy_score(y_val, tree_pred)

# Random Forest

from sklearn.ensemble import RandomForestClassifier
classifier_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_forest.fit(X_train, y_train)
forest_pred = classifier_forest.predict(X_val)
forest_loss = log_loss(y_val, forest_pred)
print(forest_loss)
forest_cm = confusion_matrix(y_val, forest_pred)
print(forest_cm)
accuracy_score(y_val, forest_pred)



# Visualising the Training set results
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier_svc2.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape), # Replace classifier_svc2 by your choice of classifier object and see how the decision boundary looks
             alpha = 0.75, cmap = ListedColormap(('orange', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

# Visualising the validation set results
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_val), y_val
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier_svc2.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape), # Repalce classifier_svc2 by your choice of classifier object and see how the decision boundary looks
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

3.7992893913630814
[[65  3]
 [ 8 24]]
2.417746331540956
[[64  4]
 [ 3 29]]
3.7992893913630814
[[66  2]
 [ 8 24]]
2.417746331540956
[[65  3]
 [ 8 24]]
3.453901627413975
[[65  3]
 [ 7 25]]
3.1085378513877737
[[62  6]
 [ 3 29]]
3.1085298554134715
[[63  5]
 [ 4 28]]
