In [1]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 14 23:40:56 2020

@author: Shoum
"""
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#Load Datasets
dataset = pd.read_csv('Data.csv') #Pandas is the most popular library to load datasets.
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values


#Deal with missing data
# Encoding the Independent Variable(X)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  # when we say strategy='mean' , we basically replace the missing value by the mean for that feature(column)
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

# Encoding categorical feature 
# =============================================================================
# If you check the first column, it has country names but machine learning cannot deal with it. It only works with numbers.
# We want to assign these categorical(category names) as numbers.
# =============================================================================
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Encoding the Dependent Variable (Y)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)



# Splitting the dataset into the Training set and Test set
# =============================================================================
# When we get our dataset, we want to divide it into training and validation set. The idea is to train the model
# only on the training set and evaluate the model on the validation set. This gives us some sense of how the model
# will work on unseen data. We then try to imrpove our model based on the results on the validation set.
# =============================================================================
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 1)
print(X_train)
print(X_val)
print(y_train)
print(y_val)



# Feature Scaling
# =============================================================================
# Sometimes we have features whose values are in different ranges. For example we can have
# a feature that has values between 0-10 and another feature that has values in thousands.
# This huge range can cause an issue and hence we want to scale it.
# =============================================================================
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer 
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_val[:, 3:] = sc.transform(X_val[:, 3:])
print(X_train)
print(X_val)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]
[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]
[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -